//! param: bibliography(逐表覆盖)
//! values: 每个可覆盖参数：全局设一个值、本表设另一个值 → 本表胜出
#import "/tests/_fixture/probe.typ": *
#show: spec.with(param: "bibliography(..) 逐表覆盖", controls: "`bibliography()` 的同名参数覆盖全局，`auto` 继承。",
  expect: [本文件*逐个*走一遍所有可覆盖参数：每块把*全局*设成一个值、把*本表*设成另一个值，
    表里印出来的必须是*本表*那个值。缺省 `auto`（或 `none`）表示「继承全局」。
    这是覆盖*链路*的测试——每个参数具体取值的语义在它自己那一节（`0x-*` 各文件）。
    ⚠️ 逐次 `#cite(..)` 的覆盖是另一条链（见 `14-per-cite/`）；
    `correct-punct` *不能*逐表覆盖（矫正在解析期一次性完成，要换得换一个 `gb7714(..)` 实例）。])
#let mixed = bytes(read("/tests/_fixture/main.bib") + read("/tests/_fixture/edge.bib"))
#let cs = (<bm-zh>, <bm-en>, <aj-zh>, <bm-online>, <bm-noauthor>, <dt-zh>, <pt-zh>, <ti-multivolume>, <rel-zh>, <an-a>, <kw-a>, <pid-isbn>)
#let ov(name, global-cfg, list-args) = case(name, global-cfg, cites: cs, bib: mixed, full: false, bib-args: list-args)

#ov("sort-keys", gb7714.with(sort-keys: [@aj-zh]), (sort-keys: [@st-zh]))
#ov("disambiguate", gb7714.with(disambiguate: false), (disambiguate: true))
#ov("sort-by", gb7714.with(bib-sort-by: ("title",)), (sort-by: ((date: "descending"),)))
#ov("sort-zh-by", gb7714.with(bib-sort-zh-by: "pinyin"), (sort-zh-by: "bihua"))
#ov("creator-idem", gb7714.with(creator-idem: none), (creator-idem: "———"))
#ov("sort-use-prefix", gb7714.with(sort-use-prefix: false), (sort-use-prefix: true))
#ov("bold-journal-volume", gb7714.with(bold-journal-volume: false), (bold-journal-volume: true))
#ov("page-range-separator", gb7714.with(page-range-separator: "-"), (page-range-separator: "～"))
#ov("page-range-style", gb7714.with(page-range-style: none), (page-range-style: "minimal"))
#ov("end-with-period", gb7714.with(end-with-period: true), (end-with-period: false))
#ov("et-al-min", gb7714.with(bib-et-al-min: 3), (et-al-min: 1))
#ov("et-al-use-first", gb7714.with(bib-et-al-use-first: 3), (et-al-use-first: 1))
#ov("entry-hanging-indent", gb7714.with(entry-hanging-indent: auto), (entry-hanging-indent: 4em))
#ov("entry-first-line-indent", gb7714.with(entry-first-line-indent: 0pt), (entry-first-line-indent: 2em))
#ov("number-placement", gb7714.with(number-placement: "column"), (number-placement: "inline"))
#ov("hyperlink", gb7714.with(hyperlink: true), (hyperlink: false))
#ov("hyperlink-title", gb7714.with(hyperlink-title: false), (hyperlink-title: true))
#ov("hyphenate", gb7714.with(hyphenate: true), (hyphenate: false))
#ov("italic-book-title", gb7714.with(italic-book-title: false), (italic-book-title: true))
#ov("italic-journal", gb7714.with(italic-journal: false), (italic-journal: true))
#ov("entry-spacing", gb7714.with(entry-spacing: auto), (entry-spacing: 1.5em))
#ov("number-gutter", gb7714.with(number-gutter: 0.65em), (number-gutter: 2em))
#ov("numbering-style", gb7714.with(numbering-style: "bracket"), (numbering-style: "paren"))
#ov("entry-lang-order", gb7714.with(entry-lang-order: ("zh", "en")), (entry-lang-order: ("en", "zh")))
#ov("name-style", gb7714.with(bib-name-style: auto), (name-style: (given-form: "full")))
#ov("show-anon", gb7714.with(show-anon: false), (show-anon: true))
#ov("show-et-al", gb7714.with(show-et-al: true), (show-et-al: false))
#ov("dedup-author-editor", gb7714.with(dedup-author-editor: false), (dedup-author-editor: true))
#ov("number-align", gb7714.with(number-align: "left"), (number-align: "right"))
#ov("number-width", gb7714.with(number-width: auto), (number-width: 3em))
#ov("period-after-creator", gb7714.with(period-after-creator: true), (period-after-creator: false))
#ov("short-journal", gb7714.with(short-journal: false), (short-journal: true))
#ov("show-mark", gb7714.with(show-mark: true), (show-mark: false))
#ov("show-medium", gb7714.with(show-medium: true), (show-medium: false))
#ov("show-sine-loco", gb7714.with(show-sine-loco: false), (show-sine-loco: true))
#ov("show-sine-nomine", gb7714.with(show-sine-nomine: false), (show-sine-nomine: true))
#ov("show-sine-anno", gb7714.with(show-sine-anno: false), (show-sine-anno: true))
#ov("show-patent-country", gb7714.with(show-patent-country: false), (show-patent-country: true))
#ov("volume-title-gutter", gb7714.with(volume-title-gutter: auto), (volume-title-gutter: 2em))
#ov("show-related", gb7714.with(show-related: true), (show-related: false))
#ov("show-url", gb7714.with(show-url: true), (show-url: false))
#ov("show-urldate", gb7714.with(show-urldate: true), (show-urldate: false))
#ov("space-before-mark", gb7714.with(space-before-mark: false), (space-before-mark: true))
#ov("space-before-pages", gb7714.with(space-before-pages: true), (space-before-pages: false))
#ov("back-ref", gb7714.with(back-ref: false), (back-ref: true))
#ov("show-degree", gb7714.with(show-degree: false), (show-degree: true))
#ov("show-annotation", gb7714.with(show-annotation: false), (show-annotation: true))
#ov("custom-drivers", gb7714.with(custom-drivers: (:)), (custom-drivers: (book: "{【逐表模板】} author . title")))
#ov("custom-terms", gb7714.with(custom-terms: (:)), (custom-terms: (et-al: (zh: "等等"))))
#ov("custom-fields", gb7714.with(custom-fields: (:)), (custom-fields: (mykw: (field: "userref", prefix: "参见："))))
#ov("custom-pids", gb7714.with(custom-pids: (:)), (custom-pids: (isbn: (prefix: "书号"))))
#ov("punct-style", gb7714.with(bib-punct-style: "full"), (punct-style: "half-with-space"))
#ov("custom-punct", gb7714.with(custom-punct: (:)), (custom-punct: (",": " ### ")))
#ov("url-break-every", gb7714.with(url-break-every: 1), (url-break-every: none))
#ov("url-break-hyphen", gb7714.with(url-break-hyphen: false), (url-break-hyphen: true))
#ov("url-break-hyphen-at-delimiters", gb7714.with(url-break-hyphen-at-delimiters: true), (url-break-hyphen-at-delimiters: false))
